# Generated by Django 4.0.6 on 2023-08-18 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('language', models.CharField(max_length=200)),
                ('poster', models.ImageField(upload_to='pics')),
                ('rating', models.FloatField()),
                ('ticket_cost', models.FloatField()),
            ],
        ),
    ]
